import {
  ArrowRight,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  CalendarDays,
  Car,
  CircleAlert,
  Clock,
  CreditCard,
  Download,
  FileCheck2,
  FileText,
  Gavel,
  Globe,
  HandCoins,
  Headset,
  House,
  Info,
  KeyRound,
  Landmark,
  ListChecks,
  LogIn,
  Mail,
  MapPin,
  MessageCircle,
  Mountain,
  Newspaper,
  Percent,
  Phone,
  QrCode,
  Receipt,
  Scale,
  Search,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Stamp,
  Store,
  Ticket,
  TrendingDown,
  UserRound,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Los datos (src/data) referencian íconos por nombre para seguir siendo
 * objetos planos; acá se resuelven a componentes de lucide-react.
 */
export const ICONS = {
  arrow: ArrowRight,
  badge: BadgeCheck,
  book: BookOpen,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  "calendar-clock": CalendarClock,
  calendar: CalendarDays,
  car: Car,
  alert: CircleAlert,
  clock: Clock,
  card: CreditCard,
  download: Download,
  "file-check": FileCheck2,
  file: FileText,
  gavel: Gavel,
  globe: Globe,
  coins: HandCoins,
  headset: Headset,
  house: House,
  info: Info,
  key: KeyRound,
  landmark: Landmark,
  list: ListChecks,
  login: LogIn,
  mail: Mail,
  pin: MapPin,
  chat: MessageCircle,
  mountain: Mountain,
  news: Newspaper,
  percent: Percent,
  phone: Phone,
  qr: QrCode,
  receipt: Receipt,
  scale: Scale,
  search: Search,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stamp: Stamp,
  store: Store,
  ticket: Ticket,
  discount: TrendingDown,
  user: UserRound,
  users: Users,
  wallet: Wallet,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const C = ICONS[name];
  return <C className={className} aria-hidden="true" />;
}
